package net.egelke.android.eid.model;

public enum DocumentType {
	BELGIAN_CITIZEN,
	KIDS_CARD,
	BOOTSTRAP_CARD,
	HABILITATION_CARD,
	FOREIGNER_A,
	FOREIGNER_B,
	FOREIGNER_C,
	FOREIGNER_D,
	FOREIGNER_E,
	FOREIGNER_E_PLUS,
	FOREIGNER_F,
	FOREIGNER_F_PLUS,
	EUROPEAN_BLUE_CARD_H
}
